[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"

#http.check-revoke = false

[source.ustc]
registry = "https://mirrors.ustc.edu.cn/crates.io-index"

# replace-with = 'ustc'

[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld",
    "-Cforce-frame-pointers=yes"
]
